name: heygen
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.3.2

# dependencies:

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
